let body="id": 0,
  "felhasznaloNev": "string",
  "teljesNev": "string",
  "salt": "string",
  "hash": "string",
  "email": "string",
  "aktiv": 0,
  "regisztracioDatuma": "2025-01-15T16:26:36.196Z",
  "profilKepUtvonal": "string",